service: gasnatur

provider:
    name: aws
    region: us-east-1
    runtime: provided.al2
    environment:
        APP_ENV: prod

plugins:
    - ./vendor/bref/bref

functions:
    api:
        handler: index.php
        description: ''
        timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
        layers:
            - ${bref:layer.php-74-fpm}
        events:
            - http:
                path: /
                method: ANY
            - http:
                path: /{any+}
                method: ANY

# Exclude files from deployment
package:
    exclude:
        - 'node_modules/**'
        - 'tests/**'
